#
# Thank you for purchasing PinataParty and I hope you enjoy the plugin!
# If you have any issues please refer to the "HELP/HOW TO" on the plugin page below!
# Plugin page: https://www.spigotmc.org/resources/59318/
#
# !!! Some settings can ONLY be changed with a full server restart NOT reload !!!
#
# Helpful links:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html

# Check for plugin updates on startup and every 24 hours?
update-notify: true

# Should we save the data.yml every so often to ensure no data loss on any crashes?
save-task: true
# Time in seconds (Default 1800 / 30 mins).
# Recommended to be at least 300+.
save-timer: 1800

# Should we send a message to all players online telling them to vote (ONLY if they haven't in the last 24 hours)
# The edit-able message in further down in the config under "message".
vote-reminder: true
# Time in seconds (Default 10800 / 3 hours).
# Recommended to be at least 3600+.
vote-reminder-timer: 10800
# Sound to play to the player.
# NONE for no sound.
# SOUND:VOLUME:PITCH
vote-reminder-sound: ENTITY_PLAYER_LEVELUP:1.15:1.35

# Change this if you want to use the permissions for pinataparty.hitamount.(number).
# When a player logs in and when the Pinata get summoned it will do a check for the player
# to get their max hit amount from the permisions.
#
# If you don't want to use the permissions for max hit then leave this 1
# else if you want to, put this number to be the max permission you will give to a player.
max-player-hit-amount: 1

# Enable/Disable PinataParty listening for votes.
# Disable this if you are only interested in the commands/pinata
# and use another plugin for registering votes.
listen-for-votes: true

# Only allow certain items to hit the Pinata.
use-material-whitelist: false
material-whitelist:
- STICK
- FISHING_ROD
- CARROT_ON_A_STICK
- WARPED_FUNGUS_ON_A_STICK
- BAMBOO

# Change how offline voting works here.
offline-voting:
   
   # Enable offline voting?
   enabled: true

   # If offline voting is enabled what should we do with offline votes?
   # Should we still send the player-vote commands when the player comes online?
   queue-commands: true
   # Should we increase the certain counters?
   increase-pinata-vote: false

# Played at the players location each time when they vote (Good feedback when tabbed)
# Will only play once on login for offline voting so it isn't ear destroying and laggy
vote-effects:

   # NONE to disable.
   # NAME:AMOUNT;XSPREAD;YSPREAD:ZSPREAD:SPEED
   particle: VILLAGER_HAPPY:50:0.50:0.90:0.50:0.05
   
   # NONE to disable.
   # SOUND:VOLUME:PITCH
   sound: ENTITY_PLAYER_LEVELUP:1:1.25
   
# Enable/Disable the /vote command - Requires restart.
# Set the output messages below in the message section.
vote-command: true

# The amount of fireworks to summon on death.
# Set to 0 to disable.
fireworks-on-death-amount: 10

# Restriction settings.
restrict-to-only-recent-voters:

   # Enable restriction to only recent voters?
   enabled: false
   
   # Time in minutes that the player had need to have
   # voted at least once to be able to hit the Pinata.
   time-period: 1440

# In-game messages.
# Set to "" for no message.
language:

    no-permission: '&cYou don''t have enough permissions.'
    spawn: '&eA pinata just spawned at %x%, %y%, %z% in %world%.'
    die: '&eThe pinata was destroyed!'
    
    pinata:
    
        teleport: '&eThe pinata teleported at &c&l%x%&e - &c&l%y%&e - &c&l%z%&e!'
        # Use <rainbow> to make it flashy.
        name: '&7» <rainbow>&lPINATA! &7«'
        hits-left: '&c&l%hit% hit%s% left!'
        # The name for the boss bar.
        # Use <rainbow> to make it flashy.
        boss-bar: '<rainbow>&lPINATA: %hit% HIT%S% LEFT'
        countdown: '<rainbow>&l%time% SECONDS TILL PINATAPARTY'
        need-to-vote: '&cYou cannot hit the Pinata since you haven''t voted recently!'
    
    money-pool:
    
        check: '&eThe pinata pool is currently &6$%current% &e/ &6$%needed%'
        not-enough: '&cYou don''t have enough money: you need $%more% more.'
        put: '&eYou successfully put &6$%money%&e in the pool.'
        cooldown:
            pool: '&eThe pinata pool is &bregenerating&e, please wait &6%left%&e seconds!'
            player: '&eThis command is on cooldown, please wait &6%left%&e seconds!'
        invalid:
            invalid: '&c%arg% is not a valid number.'
            min-max: '&cMake sure you specify an amount between %min% and %max%.'

    # The message for the reminder message send every x seconds.
    vote-reminder:
    - "&2Hey &2&l%player%"
    - "&aYou haven't voted recently! You can do &a&l/vote &aand get cool rewards for helping the server you play on!"
    
    # The message for when someone does the /vote command.
    vote-command:
    - "&a&lVoting will you get special rewards!"
    - " "
    - "&2Link 1: https://www.example.com/my-server"
    - "&aLink 2: https://www.example.com/my-server"
    - "&2Link 3: https://www.example.com/my-server"
    - "&aLink 4: https://www.example.com/my-server"

# Messages for the placeholders in case you want to change them.
# Reminder for the placeholder format: %pinataparty_<a_key_below>%
# e.g %pinataparty_votes_total%
#
# This is also just a nice list instead of visting the plugin's page.
placeholders:

   # PinataParty placeholders
   votes_left: "%amount%"
   votes_needed: "%amount%"
   current_votes: "%amount%"
   is_active: "%value%"
   active_count: "%amount%"
   
   # PinataPool placeholders
   money_left: "%amount%"
   money_needed: "%amount%"
   current_money: "%amount%"
   
   # Player placeholders
   votes_total: "%amount%"
   votes_queued: "%amount%"
   votes_total_and_queued: "%amount%"
   last_vote_time: "%time%"
   next_vote_time: "%time%"
   last_vote_time_formatted:
      
      # The format for the placeholder when there is a time
      # Follows https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
      format: "MM:dd:yyyy HH:mm:ss"
      # When the player has never voted before
      never-voted: "&cYou've never voted before!"

   next_vote_time_formatted:
      
      # The format for the placeholder when there is a time
      # Follows https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
      format: "MM:dd:yyyy HH:mm:ss"
      # When the player has never voted before
      never-voted: "&cYou've never voted before!"

   next_vote_time_countdown:
      
      # Only allows HH mm and ss
      # When the player has voted and is now showing a countdown to the next time when they can (24 hours from last vote)
      # Follows https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
      cooldown: "HH:mm:ss"
      # When the player can vote or hasn't voted before
      can-vote: "&a&lVote for rewards! /Vote"

# When enabled, the pinata will summon every X votes.
# Supports Votifier. Set votes-needed to 0 to disable.
auto-summon:

    # The amount of Pinatas to summon.
    amount: 1

    # Votes needed for the pinata to be summoned.
    votes-needed: 20
    
    # The locations for the pinata to spawn, random.
    # Set at the custom-locations section of the config!
    spawn-locations:
    - spawn

# Location used by /pinataparty spawn <location>
# as well as by the auto summon feature.
# You can add as many locations as you wish.
custom-locations:

    # spawn is the location's name.
    spawn:
        world: world
        x: 0.0
        y: 256.0
        z: 0.0

    loc2:
        world: world
        x: 621.0
        y: 162.0
        z: -82.0

# [Integration possibilities] Commands sent when ...
commands:

    # ... the countdown starts.
    countdown-start: {}
    
    # ... the countdown ends, pretty much the same as the pinata spawn.
    countdown-end: {}
    
    # ... the pinata spawns.
    spawn: {}
    
    # ... the pinata is hit by a player.
    hit:
        '1':
            chance: 50.0
            command:
            - 'minecraft:give %player% minecraft:leather 1'
        '2':
            chance: 25.0
            command:
            - 'minecraft:give %player% minecraft:iron_ingot 1'
        '3':
            chance: 10.0
            # Only works for players with this permission
            permission: "pinataparty.extrarewards"
            command:
            - 'minecraft:give %player% minecraft:diamond 1'
            - 'say %player% got a special Pinata reward!'
            
    # ... the pinata finally dies.
    # These are ran per player unless "once: true".
    die:
        '1':
            chance: 100.0
            # When enabled, the command is only ran once and doesn't replace %player%.
            once: true
            command:
            - 'say The pinata was taken down!'
        '2':
            chance: 100.0
            command:
            - 'minecraft:give %player% minecraft:diamond 12'
        '3':
            chance: 33.3
            command:
            - 'minecraft:give %player% minecraft:emerald 4'
            
    # ... a player votes (votifier).
    player-vote:
        '1':
            chance: 100.0
            command:
            - 'say %player% has voted for the server!'
        '2':
            chance: 75.0
            command:
            - 'minecraft:give %player% minecraft:iron_ingot 1'
        '3':
            chance: 37.5
            command:
            - 'minecraft:give %player% minecraft:diamond 1'
        '4':
            chance: 12.5
            command:
            - 'minecraft:give %player% minecraft:emerald 1'
            - 'say %player% got an extra special reward!'

# Give players extra rewards for voting X times total or every X time!
cumulative-rewards:
    '1': # This will give the player a reward when they vote 25 times.
        type: total # Total or Repeat, Total is when you hit a certain amount of times voted and repeat is everytime you vote x times.
        amount: 25 # The amount of votes needed for this.
        permission: "pinataparty.extrarewards" # Will only run if they have this permission, optional.
        command: # The commands to run
        - 'say %player% voted 25 total times!'
        - 'minecraft:give %player% minecraft:diamond 16'
    '2': # This will be the player a reward every 4 votes.
        type: repeat
        amount: 4
        command:
        - 'tellraw %player% {"text":"You voted 4 times and got a special reward!"}'
        - 'minecraft:give %player% minecraft:emerald 2'
        - 'minecraft:give %player% minecraft:cookie 1'
    '3':
        type: total
        amount: 50
        command:
        - 'say %player% voted 50 total times!'
        - 'minecraft:give %player% minecraft:diamond 24'
        - 'minecraft:give %player% minecraft:emerald 12'

# Pinata characteristics.
pinata:

    # Makes <rainbow> in the Pinata's name use hex colors
    # and makes it completely smooth was changing colors.
    # Only works on 1.16+.
    smooth-rainbow: true
    
    # The boss bar settings for the Pinata.
    boss-bar:
       
       # Should the Pinata have a boss bar?
       enabled: true
       
       # Should the boss bar be shown to everyone or only to players in the same world?
       global: true
       
       # The style for the boss bar (See top of config).
       style: SEGMENTED_20
       
       # The color for the boss bar (See top of config).
       # Can be RAINBOW to pick a random color each time it updates.
       # If smooth rainbow is enabled it will pick the color closest to the current rainbow hex.
       color: RAINBOW
       
       # How often should the boss bar update in ticks?
       update-rates:
       
           # The tick rate for updating the title (text) and the progress bar.
           title: 1
           # The tick rate for updating the boss bars color only if the color is RAINBOW.
           color: 2

    # The boss bar that shows for the countdown.
    countdown:
    
       # Should the Pinata have a countdown?
       enabled: true
       
       # Should the boss bar be shown to everyone or only to players in the same world?
       global: true
       
       # The style for the boss bar (See top of config).
       style: SEGMENTED_20
       
       # The color for the boss bar (See top of config).
       # Can be RAINBOW to pick a random color each time it updates.
       # If smooth rainbow is enabled it will pick the color closest to the current rainbow hex.
       color: RAINBOW
       
       # The length of the countdown in ticks.
       length: 100

       # The interval to play the count sound.
       count-interval: 20
       
       # The sounds to play for the countdown.
       sounds:
       
           # NONE to disable
           # SOUND:VOLUME:PITCH
           start: BLOCK_NOTE_BLOCK_BIT:0.5:1 # Sound to play at the start of the countdown.
           count: BLOCK_NOTE_BLOCK_BIT:0.5:0.8 # Sound to play every 1 second of the countdown.
           end: BLOCK_NOTE_BLOCK_PLING:1:0.8 # Sound to play at 0.0 seconds.
           
       # How often should the boss bar update in ticks?
       update-rates: 
       
           # The tick rate for updating the title (text) and the progress bar.
           title: 1
           # The tick rate for updating the boss bars color only if the color is RAINBOW.
           color: 2
           
    # Number of hits before the pinata explodes.
    health: 5
    # If true it will get the above health and add it self for each player online.
    # e.g if there is 4 players online and the above is 20 it'll do 20 + (20 x 4) = 100 total health!
    multiply-health-per-player-online: true
    # Limit the max health the Pinata can be multiplied to. Set to -1 to disable.
    max-multiplied-health: -1
    
    # Change the color of the Llama.
    # Use "Random" to pick a random color each Pinata.
    # Available colors: Brown, Creamy, Gray & White.
    color: White
    
    # Set to false for the Pinata to NOT have its glowing effects.
    glowing: true
    # The type of color for the pinata to have.
    # Use "Random" to pick a random color each Pinata.
    # Use "Cycle" to cycle between all the colors.
    # Available colors: Black, Dark Blue, Dark Green, Dark Aqua, Dark Red, Dark Purple
    # Gold, Gray, Dark Gray, Blue, Green, Aqua, Red, Light Purple, Yellow & White.
    glow-color: Cycle
    
    # Set to false for the Pinata to NOT have its fancy particles.
    particles: true
    # The style of particles to use for the Pinata.
    # Use "Random" to pick a random style each Pinata.
    # Available styles: Sparks, Salty, Firestorm & Waterworks.
    particles-style: Sparks
    
    # Set to false for the Pinata to NOT have its carpet
    carpet: true
    # The type of carpet for the pinata to have.
    # Use "Random" to pick a random carpet each Pinata.
    # Use "Cycle" to cycle between all the carpets.
    # Available carpets: White, Orange, Magenta, Light Blue, Yellow, Lime,
    # Pink, Gray, Light Gray, Cyan, Purple, Blue, Brown, Green, Red & Black.
    carpet-type: Cycle
    
    # Set to false for the Pinata to NOT have its chest
    chest: false
    
    # NONE to disable.
    # SOUND:VOLUME:PITCH
    hit-sound: BLOCK_SAND_BREAK:1:1
    
    # Should the Pinata be allowed to move?
    allow-movement: true
    # Pinata's speed amplifier.
    # 1 is no difference.
    speed-amplifier: 1.75
    
    # Should the Pinata use a better pathfinding method
    # where it will actively move around instead of just
    # standing there and moving once in a while like a 
    # vanilla llama (Not possible in Spigot).
    #
    # !!! ONLY SET THIS TO TRUE IF YOU USE PAPERMC AND USING 1.13+ !!!
    advanced-pathfinding:
    
        # Enabled/Disabled.
        # Speed amplifier will not do anything if this is enabled due to the new speed below.
        enabled: false
        
        # Time in ticks to get a new path/location to move to.
        interval: 20
        
        # Max range it'll try to find a pathfind location to move to.
        range: 14.0
        
        # Max Y difference it'll do to find a location to move to.
        max-y: 4.0
    
    # Cooldown of when the pinata can be hit again in seconds.
    # If you want the cooldown to be PER player and not global
    # then set the below setting to true.
    # set to 0 to disable.
    hit-cooldown: 0.85
    hit-cooldown-per-player: true

# Enable/disable/edit the pinata's abilities here.
# Abilities make destroying the pinata more challenging!
pinata-abilities:

    # The pinata teleports a few blocks away.
    teleport:
        enabled: true
        radius: 8.0
        chance: 12.0
        # 1.12 Sound: ENTITY_ENDERMEN_TELEPORT.
        # NONE to disable.
        # SOUND:VOLUME:PITCH
        sound: ENTITY_ENDERMAN_TELEPORT:1:1
        max-y: 6.0
        # Keep empty to disable.
        white-list:
        - GRASS_BLOCK
        - GRASS_PATH # <= 1.16
        - DIRT_PATH # >= 1.17
        - STONE
        - DIRT
        - SNOW
        - ICE
        
    # The pinata knocks nearby players back.
    knockback:
        enabled: true
        chance: 12.0
        radius: 6.0
        force: 1.35
        # 1.12 Sound: ENTITY_ZOMBIE_ATTACK_DOOR_WOOD.
        # NONE to disable.
        # SOUND:VOLUME:PITCH
        sound: ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR:1:1
        
    # The pinata will shoot up into the air.
    shoot-up:
        enabled: true
        chance: 8.0
        force: 1.5
        # NONE to disable.
        # SOUND:VOLUME:PITCH
        sound: ENTITY_ARROW_SHOOT:1:1
        
    # The pinata will transform into a baby.
    baby-transform:
        enabled: true
        chance: 8.0
        # Time in seconds.
        length-minimum: 2.0
        length-maximum: 8.0
        # NONE to disable.
        # SOUND:VOLUME:PITCH
        transform-in-sound: ENTITY_CHICKEN_EGG:1:1.10
        transform-out-sound: ENTITY_LLAMA_SWAG:1:0.90
        
    # The pinata will give speed and dolphins grace to nearby players.
    speed-up:
        enabled: true
        chance: 6.0
        # The level of speed/dolphin's grace.
        level: 3
        # The radius to give to players.
        radius: 12.0
        # Time in seconds.
        length-minimum: 2.50
        length-maximum: 5.0
        # NONE to disable.
        # SOUND:VOLUME:PITCH
        sound: ITEM_TRIDENT_RIPTIDE_1:1:1.25

# When enabled, the pinata will summon after players put
# $X in the pinata money pool using /pinatapool <amount>.
money-pool:

    # Money needed to auto-summon a pinata.
    # Set to 0 to disable.
    money-needed: 10000.0
    
    command:
    
        # /pinatapool command cooldown.
        cooldown: 240
        
        # Min and max values of the money
        # you can put in the pool.
        min: 10.0
        max: 10000.0
    
    # The cooldown, in seconds, of two
    # consecutive pinata pool auto summons.
    cooldown: 600
    
    # The locations for the pinata to spawn, random.
    # Set at the custom-locations section of the config!
    spawn-locations:
    - spawn