name: NoMonsterPickup
main: dev.mrfloris.nopickup.NoMonsterPickup
version: 1.1.0
api-version: '1.21'
description: Cancels item pickups for Monster entities; allows Piglins for bartering. Thanks Killian
author: mrfloris
